export const siteConfig = {
  name: "Clave Studio Digital",
  shortName: "Clave",
  url: "https://clavestudio.dev",
  email: "hola@clavestudio.dev",
  phoneDisplay: "092 395 129",
  phoneE164: "+59892395129",
  whatsappUrl: "https://wa.me/59892395129",
  instagramHandle: "@clavestudiodigital",
  instagramUrl: "https://instagram.com/clavestudiodigital",
  locale: "es_419",
  defaultTitle: "Clave Studio Digital - Agencia Digital para Pymes en LATAM",
  defaultDescription:
    "Estudio digital para pymes en LATAM. Creamos sitios web, tiendas online y automatizaciones para negocios que necesitan vender mejor, verse bien en Google y operar con más claridad.",
  ogDescription:
    "Desarrollo web, e-commerce y automatizaciones para pymes en LATAM, con foco comercial fuerte en Uruguay.",
  keywords: [
    "agencia digital latam",
    "desarrollo web latam",
    "e-commerce latam",
    "automatizaciones latam",
    "agencia digital uruguay",
    "desarrollo web uruguay",
    "e-commerce uruguay",
    "tienda online uruguay",
    "automatizaciones uruguay",
    "agencia web pymes",
    "shopify uruguay",
    "desarrollo frontend uruguay",
  ],
  routes: {
    home: "/",
    services: "/servicios",
    about: "/sobre-nosotros",
    blog: "/blog",
    privacy: "/privacidad",
    terms: "/terminos",
    agenciaDigitalLatam: "/agencia-digital-latam",
    desarrolloWebLatam: "/desarrollo-web-latam",
    ecommerceLatam: "/ecommerce-latam",
    automatizacionesLatam: "/automatizaciones-latam",
    agenciaDigitalUruguay: "/agencia-digital-uruguay",
    desarrolloWebUruguay: "/desarrollo-web-uruguay",
    ecommerceUruguay: "/ecommerce-uruguay",
    automatizacionesUruguay: "/automatizaciones-uruguay",
  },
} as const
